### ISSUE TITLE
Not working for bonds

### ISSUE THREAD

**Issue by OGsiji** [alvarobartt/investiny#11]
```
from investiny import historical_data, search_assets

search_results = search_assets(query='U.K. 10Y', limit=1, type="bond")
investing_id = int(search_results[0]["ticker"])
```

` list index out of range`

**Comment by alvarobartt** [comment]
Hi @OGsiji so the filter is named "Bond Yield" not "bond", but besides that, I've tried it and it doesn't work with the `filter` indeed, so you can remove the filter in the meantime so as to get the results 😄

**Comment by alvarobartt** [comment]
Hi again @OGsiji already found the fix, just rename the `filter="bond"` to `filter="Yield"`. Anyway I'll release the changes ASAP 😄

**Comment by OGsiji** [comment]
Make sense, Thanks
