### ISSUE TITLE
volume data

### ISSUE THREAD

**Issue by plutoBase** [alvarobartt/investiny#17]
First of all thanks very much for this, Alvaro, your efforts are hugely appreciated!

Therefore I feel a bit bad asking for more, but am wondering whether it is possible to include volume data which was available for at least some of the indices?

Again many thanks!

**Comment by alvarobartt** [comment]
Hi @plutoBase no worries, feel free to ask anything that you think it's missing and I'll try my best to integrate it!

So for the volume that's completely feasible, so I'll do it for the next release 🎉
