### ISSUE TITLE
make compatible with python 3.8 and some improvements

### ISSUE THREAD

**Issue by GSLabIt** [alvarobartt/investiny#18]
* make compatible with python 3.8
* `historical_price` seems to return a dict of list like this:
```
{
'date': ['09/01/2022', '09/02/2022', '09/05/2022', '09/06/2022', '09/07/2022', '09/08/2022', '09/09/2022', '09/12/2022', '09/13/2022', '09/14/2022', '09/15/2022', '09/16/2022', '09/19/2022', '09/20/2022', '09/21/2022', '09/22/2022', '09/23/2022', '09/26/2022', '09/27/2022', '09/28/2022', '09/29/2022'], 
'open': [147.49000549316, 147.77000427246, 149.07000732422, 147.77000427246, 147.02000427246, 145.33000183105, 143.13999938965, 143.52000427246, 144.16999816895, 143.25999450684, 143.58000183105, 142.97999572754, 143.19000244141, 142.39999389648, 140.86000061035, 141.16000366211, 140.13999938965, 139.19999694824, 137.69999694824, 137, 138.33000183105], 
'high': [147.83000183105, 149.10000610352, 149.25, 149.02000427246, 147.88000488281, 145.80999755859, 144.47999572754, 144.55999755859, 144.4700012207, 143.86999511719, 143.63000488281, 143.24000549316, 143.25999450684, 142.58000183105, 141.97999572754, 142.02000427246, 140.99000549316, 139.2200012207, 139.28999328613, 138.74000549316, 138.49000549316], 
'low': [146.7799987793, 147.13999938965, 147.36999511719, 146.67999267578, 146.74000549316, 143.05999755859, 142.46000671387, 142.91000366211, 143, 142.64999389648, 142.74000549316, 142.14999389648, 142.17999267578, 140.5299987793, 140.72999572754, 139.89999389648, 138.44999694824, 137.41000366211, 136.61999511719, 135.52000427246, 136.2200012207], 
'close': [147.38999938965, 148.33000183105, 147.72999572754, 147.27000427246, 147.5299987793, 143.16000366211, 143.57000732422, 144.5, 143.38999938965, 143.63000488281, 143.2200012207, 142.72999572754, 142.61999511719, 140.69999694824, 141.19999694824, 140.02000427246, 139.47999572754, 138.86999511719, 137.13999938965, 137.91000366211, 137.5]
}
```
would be nice to have an option to return a `pandas.DataFrame` with `date` as `index`, kind of:

```
df = pd.DataFrame.from_dict(data, orient ='columns')
df = df.set_index('date')

                  open        high         low       close
date
09/01/2022  147.490005  147.830002  146.779999  147.389999
09/02/2022  147.770004  149.100006  147.139999  148.330002
09/05/2022  149.070007  149.250000  147.369995  147.729996
09/06/2022  147.770004  149.020004  146.679993  147.270004
09/07/2022  147.020004  147.880005  146.740005  147.529999
09/08/2022  145.330002  145.809998  143.059998  143.160004
09/09/2022  143.139999  144.479996  142.460007  143.570007
09/12/2022  143.520004  144.559998  142.910004  144.500000
09/13/2022  144.169998  144.470001  143.000000  143.389999
09/14/2022  143.259995  143.869995  142.649994  143.630005
09/15/2022  143.580002  143.630005  142.740005  143.220001
09/16/2022  142.979996  143.240005  142.149994  142.729996
09/19/2022  143.190002  143.259995  142.179993  142.619995
09/20/2022  142.399994  142.580002  140.529999  140.699997
09/21/2022  140.860001  141.979996  140.729996  141.199997
09/22/2022  141.160004  142.020004  139.899994  140.020004
09/23/2022  140.139999  140.990005  138.449997  139.479996
09/26/2022  139.199997  139.220001  137.410004  138.869995
09/27/2022  137.699997  139.289993  136.619995  137.139999
09/28/2022  137.000000  138.740005  135.520004  137.910004
09/29/2022  138.330002  138.490005  136.220001  137.500000

```

**Comment by alvarobartt** [comment]
Thanks for your proposals @GSLabIt, I agree with making it compatible with Python 3.8 but regarding the addition of the `pandas` dependency I'm not sure, as I want to keep `investiny` tiny as its name says, so I don't think that using `pandas` makes sense here, but I'll add an entry in the documentation for integrations and there include the explanation on how to transform the output into a `pandas.DataFrame`, would that be ok?

Thank you again!

**Comment by GSLabIt** [comment]
> Thanks for your proposals @GSLabIt, I agree with making it compatible with Python 3.8 but regarding the addition of the `pandas` dependency I'm not sure, as I want to keep `investiny` tiny as its name says, so I don't think that using `pandas` makes sense here, but I'll add an entry in the documentation for integrations and there include the explanation on how to transform the output into a `pandas.DataFrame`, would that be ok?
> 
> Thank you again!

it is ok.. I'll add my code

**Comment by maread99** [comment]
Seems appropriate to mention here that I'm intending to add `investiny` as a data source for [market_prices](https://github.com/maread99/market_prices), hopefully next month. The interface should be exactly the same as with the existing `PricesYahoo` class, so...
- prices will be returned as a pandas `DataFrame`
- you can request any interval (limited only by availability of underlying data)
- data's cached (never requests the same data twice)
- you get a [host of functionality](https://github.com/maread99/market_prices#features-include) related to knowledge of the underlying exchange's trading calendar

@alvarobartt, given your plan to keep `investiny` tiny, I think `market_prices` could prove to be a nice extension to handle post-processing of prices (and indeed evaluation of the period to query). Currently its minimum supported python version is 3.8. I wasn't intending to move to 3.9 quite yet. If it makes little difference to you, I'd certainly appreciate it if you could drop the minimum requirement here to 3.8!

(Great work on introducing intraday price data! 🎉)

**Comment by alvarobartt** [comment]
Thanks for understading, @GSLabIt! And, @maread99 I don't have much free time but I'll try to check it at some point, in the meantime I can tell you that I'll make `investiny` support Python 3.8+ instead of Python 3.9+ in the next release (v0.5.0 if I'm not mistaken) coming later this weekend 👍🏻

**Comment by GSLabIt** [comment]
> Thanks for understading, @GSLabIt! And, @maread99 I don't have much free time but I'll try to check it at some point, in the meantime I can tell you that I'll make `investiny` support Python 3.8+ instead of Python 3.9+ in the next release (v0.5.0 if I'm not mistaken) coming later this weekend 👍🏻 

Could you add info on where to find `investing_id`?

**Comment by alvarobartt** [comment]
Hi @GSLabIt, sure I'll add a documentation entry on how to retrieve the Investing.com IDs (`investing_id` param), but you can find details on how to actually retrieve it by chaining the functions `search_assets` and `historical_data` at https://alvarobartt.github.io/investiny/usage/
