### ISSUE TITLE
There is another api server from investing.com which works same 

### ISSUE THREAD

**Issue by ramakrishnamekala129** [alvarobartt/investiny#20]
import requests
from requests.structures import CaseInsensitiveDict

url = "https://tvc6.investing.com/e44855091c7412b1c8473adb2d797c8b/1665109080/1/1/8/history?symbol=252&resolution=5&from=1664677140&to=1665109200"

headers = CaseInsensitiveDict()
headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
headers["Accept"] = "*/*"
headers["Accept-Language"] = "en-US,en;q=0.5"
headers["Referer"] = "https://tvc-invdn-com.investing.com/"
headers["Content-Type"] = "text/plain"
headers["Origin"] = "https://tvc-invdn-com.investing.com"
headers["Connection"] = "keep-alive"
headers["Sec-Fetch-Dest"] = "empty"
headers["Sec-Fetch-Mode"] = "cors"
headers["Sec-Fetch-Site"] = "same-site"

resp = requests.get(url, headers=headers)

print(resp.status_code)

**Comment by ramakrishnamekala129** [comment]
we can switch between these api server for better speed

**Comment by alvarobartt** [comment]
Hi, @ramakrishnamekala129 thanks for that! So I'm still figuring out how to add it, as it can either be a random selection of URL or just use `tvc4` until it stops working then try with `tvc6`, but as the referer and the origin are the same, I assume that if you're blocked in one you're blocked in the other... So let's keep this aside as a future TODO 🤗
