### ISSUE TITLE
ModuleNotFoundError: No module named 'pip'

### ISSUE THREAD

**Issue by Vincenzocarandente** [alvarobartt/investiny#21]
When i do "pip install investiny" colab return the writing in the title. How can i fix?

**Comment by alvarobartt** [comment]
Hi @Vincenzocarandente in order to install it in Google Colab you'll need to `!pip install investiny`, note the starting exclamation sign `!`.

Anyway, restart the cluster, as Google Colab's Python already comes with `pip` installed 👍🏻

**Comment by Vincenzocarandente** [comment]
Sadly same result
![hfureifheriufr](https://user-images.githubusercontent.com/58863931/194705157-4efb16af-58b0-4fee-9714-898d3d9c718f.PNG)
