### ISSUE TITLE
Getting incorrect Date and Prices

### ISSUE THREAD

**Issue by KapsTrvl** [alvarobartt/investiny#31]
![image](https://user-images.githubusercontent.com/73245978/195154483-723f7e72-3d6b-40b0-84a4-97127cad0ee4.png)

![image](https://user-images.githubusercontent.com/73245978/195154610-6e37d720-84a2-4198-ab6e-38e3fa42d09f.png)

I seem to be getting incorrect date and price mapping. I you check the images, 10/02/2022 and 10/09/22 are Sundays. Cross checked on investing.com and seems price output are moved back by a day.

** limited knowledge of running code, so might be doing something wrong at my end.. but will great if you take a look.

**Comment by KapsTrvl** [comment]
Hi @alvarobartt .. the mapping issue with AAPL got resolved post upgrading to latest version.

![image](https://user-images.githubusercontent.com/73245978/195999825-77ed4e9c-d9cf-4526-8bee-026a21059d0f.png)

![image](https://user-images.githubusercontent.com/73245978/195999872-0d55b5fc-c0e5-4673-bcdf-2ed7ee500955.png)

However see below for US10Y, getting weekend date 10/08/22 (Sat) and missing 10/10/22(Mon) -

![image](https://user-images.githubusercontent.com/73245978/195999971-a3ae2469-52f3-4709-89d2-d779744069fc.png)

![image](https://user-images.githubusercontent.com/73245978/196000038-c3ea3861-bba6-4f9d-8a8e-d5a8da6a47d1.png)

Thanks

**Comment by alvarobartt** [comment]
> Hi @alvarobartt .. the mapping issue with AAPL got resolved post upgrading to latest version.
> 
> ![image](https://user-images.githubusercontent.com/73245978/195999825-77ed4e9c-d9cf-4526-8bee-026a21059d0f.png)
> 
> ![image](https://user-images.githubusercontent.com/73245978/195999872-0d55b5fc-c0e5-4673-bcdf-2ed7ee500955.png)
> 
> However see below for US10Y, getting weekend date 10/08/22 (Sat) and missing 10/10/22(Mon) -
> 
> ![image](https://user-images.githubusercontent.com/73245978/195999971-a3ae2469-52f3-4709-89d2-d779744069fc.png)
> 
> ![image](https://user-images.githubusercontent.com/73245978/196000038-c3ea3861-bba6-4f9d-8a8e-d5a8da6a47d1.png)
> 
> Thanks

Mmm that's true... can you please open a separate issue for that? I'll check what is `investpy` doing with the dates before returning those so as to stop this issue and make the data consistent. @KapsTrvl Thanks :hugs:
