### ISSUE TITLE
pip install error in Linux

### ISSUE THREAD

**Issue by gianandreabertello** [alvarobartt/investiny#38]
Installation in Windows machine went smoothly
That on Linux reported this error message. Anything I can do to fix it?

/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement investiny (from versions: none)
ERROR: No matching distribution found for investiny

**Comment by orestisf** [comment]
Can it be that your Python version is < Python 3.8?

**Comment by alvarobartt** [comment]
Hi @gianandreabertello, as @orestisf is saying, it can be due to the Python version that you're using, as `investiny` is just supported in Python 3.8 and above, as stated at https://alvarobartt.github.io/investiny/requirements.

Anyway, in order to avoid these problems with issues being hard to understand sometimes, I'll create some issue templates so that the creation requires a minimum fulfilment of some basic fields, such as `investiny` version, Python version, etc.

**Comment by datatalking** [comment]
> Anyway, in order to avoid these problems with issues being hard to understand sometimes, I'll create some issue templates so that the creation requires a minimum fulfilment of some basic fields, such as `investiny` version, Python version, etc.

@alvarobartt Would this template work?

I can send you a PR later today

```
### Issue and Steps to Reproduce
<!-- Describe your issue and tell us how to reproduce it (include any useful information). -->

### Versions

### Screenshots

#### Expected

#### Actual

### Additional Details
* Installed packages:
* 
```

**Comment by alvarobartt** [comment]
Hi @datatalking thanks for the help, but I already have a branch ready to be pushed with some issue templates for bug reports, features/enhancements, and other issues, just some minor things to check, so there's no need for you to submit that issue template! But thank you anyway, once I push mines you can edit those if you think that there's any missing information, thanks again 🤗
