### ISSUE TITLE
Patiently waiting for search_quotes

### ISSUE THREAD

**Issue by hamzaahmedzia1** [alvarobartt/investiny#4]
I have download the list of all stocks on my countries exchange in two separate files ( two separate exchanges) from investing.com screener page by clicking on download results.

The downloaded csv contains the name and symbol but not the _investing_id_ required for downloading the historical prices.

My idea is to loop through all name or symbol calling search_quotes to retrieve the _investing_id_ from the search results and then store it some place safe.

Then I want to loop through the _investing_id_ list to retrieve historical data. 

Therefore patient.

**Comment by alvarobartt** [comment]
Hi, @hamzaahmedzia1 that feature is currently under development, once I release 0.2.0 I'll prepare the release of 0.3.0 including the function to search assets in Investing.com 🤗

**Comment by hamzaahmedzia1** [comment]
Thank you so much @alvarobartt ; just love it. Your updated documentation makes my day.
