### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by joao-pm-santos96** [alvarobartt/investiny#53]
Hi,

I have just started receiving error 403... (https://github.com/alvarobartt/investpy/issues/613). Can someone confirm that is a general issue or just something on my end?

Thank you,

**Comment by alvarobartt** [comment]
Hi, @joao-pm-santos96 this has already been fixed, and released, it's available at https://github.com/alvarobartt/investiny/releases/tag/v0.7.2, should be installable in some minutes with `pip install investiny==0.7.2` :hugs:

**Comment by alvarobartt** [comment]
FYI after some testing, it seems that `tvc4` is working again! 🎉

**Comment by martinemilander** [comment]
@joao-pm-santos96 I'm having the same issue, getting 403 error. I have 0.7.2 installed.

**Comment by alvarobartt** [comment]
Yes @martinemilander indeed it was just working for some requests, then I received the HTTP 403 error again... Sorry for the confusing information!
